version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
    overwrite: true
    exclude:
      - appspec.yml
      - scripts/**
      - .git/**

permissions:
  - object: /var/www/html
    owner: nginx
    group: nginx
    mode: 755
    pattern: "**"
    type: "directory"
  - object: /var/www/html
    owner: nginx
    group: nginx
    mode: 644
    pattern: "**"
    type: "file"

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/configure_nginx.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: root
